# Generated by Django 4.2.23 on 2025-09-05 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="rateplan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="reservations.rateplan",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="qr_token",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
